"""Prompt templates and definitions for AI analysis."""

from .modular_prompts import (
    VISUAL_PROMPTS,
    AUDIO_PROMPTS,
    MULTIMODAL_PROMPTS,
    STAGE_ZERO_PROMPTS,
    SYNTHESIS_FINAL_INTEGRATION_PROMPT,
    KINESIC_EVENT_LOG_PROMPT,
    BASELINE_ESTABLISHMENT_PROMPT,
    DEEPFAKE_DETECTION_PROMPT,
    AUDIO_LINGUISTIC_COMBINED_PROMPT,
)
from .prompts import (
    SAM_CHRISTENSEN_PROMPT,
    FBI_SYNTHESIS_PROMPT,
    GEMINI_COMPREHENSIVE_PROMPT,
    AUDIO_ANALYSIS_PROMPT,
    LIWC_ANALYSIS_PROMPT,
    DEV_META_ANALYSIS_PROMPT,
)

__all__ = [
    # Modular prompts
    'VISUAL_PROMPTS',
    'AUDIO_PROMPTS',
    'MULTIMODAL_PROMPTS',
    'STAGE_ZERO_PROMPTS',
    'SYNTHESIS_FINAL_INTEGRATION_PROMPT',
    'KINESIC_EVENT_LOG_PROMPT',
    'BASELINE_ESTABLISHMENT_PROMPT',
    'DEEPFAKE_DETECTION_PROMPT',
    'AUDIO_LINGUISTIC_COMBINED_PROMPT',
    # Legacy prompts
    'SAM_CHRISTENSEN_PROMPT',
    'FBI_SYNTHESIS_PROMPT',
    'GEMINI_COMPREHENSIVE_PROMPT',
    'AUDIO_ANALYSIS_PROMPT',
    'LIWC_ANALYSIS_PROMPT',
    'DEV_META_ANALYSIS_PROMPT',
]
